# docker-compose.yml

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - shared_volume:/usr/local/apache2/htdocs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - /Users/daeheekim/repos/apache-elk/elasticsearch/data:/usr/share/elasticsearch/data
    #  - shared_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /Users/daeheekim/repos/apache-elk/logstash/data:/usr/share/logstash/data
     # - shared_volume:/usr/share/logstash/data
    ports:
      - "5000:5000"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - /Users/daeheekim/repos/apache-elk/kibana/data:/usr/share/kibana/data
    ports:
      - "5601:5601"

volumes:
  shared_volume:
